---
apiVersion: v1
kind: Service
metadata:
  name: palindrome-service
spec:
  type: NodePort
  selector:
    app: palindrome-app
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 30001

---
apiVersion: v1
kind: Secret
metadata:
  name: mongocreds
type: Opaque
data:
  user: UGFsaW5kcm9tZVVzZXI= 
  password: MTIz    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palindrome-app
  labels:
    app: palindrome-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: palindrome-app
  template:
    metadata:
      labels:
        app: palindrome-app
    spec:
      containers:
      - name: palindrome-container
        image: palindrome-img:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        env:
        - name: MONGOUSER
          valueFrom:
            secretKeyRef:
              name: mongocreds
              key: user
        - name: MONGOPASS
          valueFrom:
            secretKeyRef:
              name: mongocreds
              key: password
        ports:  
        - containerPort: 9091