# Default values for palindrome-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: palindrome-img
  pullPolicy: IfNotPresent
  tag: "latest"

label: palindrome-app 

appPort: 9091
nodePort: 30001

service:
  type: NodePort
